name: coop_control_app
description: Control de inventarios, caja y ventas con exportación a PDF y Excel.
publish_to: "none"
version: 1.1.0+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: any
  shared_preferences: any
  pdf: any
  printing: any
  excel: ^4.0.6
  share_plus: any
  path_provider: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
